name: CI

on:
  pull_request:
    branches: ["develop", "master"]
  push:
    ##
    # DO NOT FORGET TO UPDATE THE "if" STATEMENTS BELOW!
    ##
    tags: ["*"]
    branches: ["master"]

jobs:
  build-test-deploy:
    name: Build, Test, Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{  secrets.DOCKER_PASSWORD }}

      - uses: olegtarasov/get-tag@v2.1.2
        id: tag-name

      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with:
          length: 7

      - name: Preview image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: docker.io/perrorone/sourcify:${{ steps.short-sha.outputs.sha }}-${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,author,eventName,workflow,ref,commit
          channel: "#random"
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
